server:
  port: 8081
  servlet:
    session:
      cookie:
        secure: true
    encoding:
      charset: utf-8
      force: true
      enabled: true
spring:
  application:
    name: back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/komeiji?serverTimezone=UTC&useSSL=false
    username: root
    password: komeiji
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: 127.0.0.1
      port: 6379

swagger: